on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}

jobs:
  # brain:
  #   name: Build and deploy brain
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Setup gcloud
  #       uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
  #       with:
  #         version: '290.0.1'
  #         service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  #         project_id: ${{ secrets.PROJECT_ID }}
  #         export_default_credentials: true
  #     - name: Configure docker credentials
  #       run: gcloud auth configure-docker
  #     - name: Build
  #       working-directory: brain
  #       run: docker build . -t gcr.io/$PROJECT_ID/brain
  #     - name: Push
  #       run: docker push gcr.io/$PROJECT_ID/brain
  #     - name: Deploy
  #       run: gcloud run deploy brain --image gcr.io/$PROJECT_ID/brain --platform managed --region asia-southeast1 --allow-unauthenticated
  brain:
    name: Build and deploy brain
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true
      - name: Configure docker credentials
        run: gcloud auth configure-docker
      - name: Build
        working-directory: brain
        run: docker build . -t gcr.io/$PROJECT_ID/brain
      - name: Push
        run: docker push gcr.io/$PROJECT_ID/brain
      # - name: Deploy
      #   run: |
      #     gcloud compute instances update-container brain --zone asia-southeast1-b \
      #     --container-image gcr.io/$PROJECT_ID/brain:latest
  telegram:
    name: Build and deploy telegram
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true
      - name: Configure docker credentials
        run: gcloud auth configure-docker
      - name: Build
        working-directory: telegram
        run: docker build . -t gcr.io/$PROJECT_ID/telegram
      - name: Push
        run: docker push gcr.io/$PROJECT_ID/telegram
      - name: Deploy
        run: gcloud run deploy telegram --image gcr.io/$PROJECT_ID/telegram --platform managed --region asia-southeast1 --allow-unauthenticated